services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENABLE_SWAGGER: "${ENABLE_SWAGGER:-0}"
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      PORT: "${PORT:-3000}"
      DATABASE_URL: ${DATABASE_URL?err}
      JWT_SECRET: ${JWT_SECRET?err}
    env_file:
      - .env
