# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

env:
  DATABASE_URL: mongodb://localhost:27017/test
  JWT_SECRET: jwt_secret

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
      - run: npm i -g pnpm@10.11
      - run: pnpm i
      - run: pnpm prisma generate

      - run: pnpm test:cov

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 6.0
          mongodb-replica-set: test-rs

      - run: pnpm test:e2e

      # https://github.com/marketplace/actions/jest-coverage-comment
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: Test Report
          multiple-junitxml-files: |
            Unit, ./coverage/junit.xml
            E2E, ./coverage/junit-e2e.xml
          coverage-path: ./coverage/coverage.txt
          coverage-path-prefix: src/
