# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci

      - run: npm run test:cov

      - run: npm run test:e2e

      # https://github.com/marketplace/actions/jest-coverage-comment
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: Test Report
          multiple-junitxml-files: |
            Unit, ./coverage/junit.xml
            E2E, ./coverage/junit-e2e.xml
          coverage-path: ./coverage/coverage.txt
          coverage-path-prefix: src/
